### ISSUE TITLE
GitHub meetup #3: 6 de marzo

### ISSUE THREAD

**Issue by JJ** [JJ/top-github-users-data#12]
Tras el éxito del #7 , vamos a por el siguiente. Creo recordar que @iblancasa tenía tema para contar, pero también @m42 o, en general, quien quiera. Cambiaremos el sitio para irnos a la sala Generalife, en la 3ª planta del edificio, pero será en el mismo lugar. Ah, y las cervezas fuera. ¿Más ideas @stringparser @psicobyte @fdavidcl y los demás?

**Comment by iblancasa** [comment]
Me parece bien (y podré ir) :D

**Comment by stringparser** [comment]
De lujo @JJ! You añadir, para el que pase por aquí, que @JJ ha hecho una [organización de github para usuarios de granda](https://github.com/github-users-grx) :smiley_cat:

**Comment by agarciamontoro** [comment]
La idea suena genial :)
Pero si no estoy muy equivocado muchos de los que estuvimos este viernes tenemos las clases por la tarde el cuatrimestre que viene. Yo no tendría mucho inconveniente en no ir a clase una vez al mes, vamos, pero por si veis mejor otro día.

Gracias por las cervezas, por cierto *____*

**Comment by stringparser** [comment]
A mi me da igual el día

**Comment by iblancasa** [comment]
Yo lo prefiero ese día... es el que mejor me viene

**Comment by M42** [comment]
Entre @pbaeyens y yo preparamos hace un tiempo una introducción a Haskell para los seminarios del doble grado. Expandiéndola un poco, tenemos un tema interesante para contar otro día. Si os parece bien, nos la preparamos para abril.

¡Un saludo!

**Comment by JJ** [comment]
OK.

El 8 de febrero de 2015, 12:23, Mario Román <notifications@github.com>
escribió:

> Entre @pbaeyens <https://github.com/pbaeyens> y yo preparamos hace un
> tiempo una introducción a Haskell para los seminarios del doble grado.
> Expandiéndola un poco, tenemos un tema interesante para contar otro día. Si
> os parece bien, nos la preparamos para abril.
>
> ¡Un saludo!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/12#issuecomment-73406784>
> .
>



-- 
JJ

**Comment by JJ** [comment]
Dile a @pbaeyens que se ponga la ciudad en el perfil :-)

El 8 de febrero de 2015, 12:24, JJ Merelo <jjmerelo@gmail.com> escribió:

> OK.
>
> El 8 de febrero de 2015, 12:23, Mario Román <notifications@github.com>
> escribió:
>
>> Entre @pbaeyens <https://github.com/pbaeyens> y yo preparamos hace un
>> tiempo una introducción a Haskell para los seminarios del doble grado.
>> Expandiéndola un poco, tenemos un tema interesante para contar otro día. Si
>> os parece bien, nos la preparamos para abril.
>>
>> ¡Un saludo!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JJ/top-github-users-data/issues/12#issuecomment-73406784>
>> .
>>
>
>
>
> --
> JJ
>



-- 
JJ

**Comment by pbaeyens** [comment]
Hecho! :)

**Comment by JJ** [comment]
Call moved to  #17
