### ISSUE TITLE
Una web para el repositorio

### ISSUE THREAD

**Issue by stringparser** [JJ/top-github-users-data#13]
Hablado antes en #4. 

He estado pensando y quizás ni sea necesario hosting, podríamos tirar de github pages y hacerlo todo lo más sencillo posible. Usando AJAX, el mismo repositorio podría convertirse en la base de datos de una forma u otra. 

Este fin de semana me viene y poco largo ya para esto, pero para el que viene preparo un borrador si os parece. Si no, lo que buenamente propongáis. Lo de arriba es una idea :)

**Comment by stringparser** [comment]
Y en cuanto a CORS, mirar [aquí](http://stackoverflow.com/questions/18923328/is-there-a-way-to-enable-cors-on-github-pages)

**Comment by iblancasa** [comment]
Le envié a @JJ las credenciales de una máquina virtual Fiware. Es un IaaS y está siempre online. 
Podríamos montar algo como lo que empecé a hacer yo [aquí](http://iblancasa.com/top-github-users-data-spain/) y [aquí está el repo](https://github.com/iblancasa/top-github-users-data-spain/tree/gh-pages) y tener una parte tipo como la gente de [DevOPS Valencia](http://www.valenciadevops.me/) que nos ayudaría a difundir esto y que viniera más gente

**Comment by stringparser** [comment]
¡Hostia! pero si ya está :D. Perfecto pues si acaso añadirle algunas cosillas y listo. 

El repo que dejas sería solo en parte lo que hay en el navegador. ¿Cómo tienes montado el servidor?

**Comment by iblancasa** [comment]
Es una gh-pages.

Si miras el mapa.js, verás que las ciudades se declaran así:

```javascript

  var granada = new google.maps.LatLng(37.1809462,-3.5922032);
  var granadaG = new google.maps.Marker({
    position: granada,
    map: map,
    icon: image
  });

  google.maps.event.addListener(granadaG, 'click', function() {
    $("#ciudad").hide(500);
    $.get(  dir+"top-Granada.html", function( data ) {
      $( "#ciudad" ).html( data );
    });
    $("#ciudad").show(500);
  });
```

Cuando hago la generación del ranking, en el formated, no solo creo el fichero markdown. También hago un fichero HTML, que tiene una tabla y se listan los usuarios de GitHub (lo mismo que hace el markdown, pero con HTML).

Una vez declarado el iconito para la ciudad y tal, se añade un evento que lo que hace es cargar ese HTML usando AJAX

**Comment by stringparser** [comment]
Siii, que soy un bocas :). Estaba a punto de escribir porque mirando mejor me estaba dando cuenta de lo que estabas haciendo. Esta muy bien, a ver que te parece esto:

La generación el paso de generación se puede saltar si usamos [react.js](http://github.com/facebook/reactjs) y el código se podría mantener actualizando el json simplemente.

**Comment by stringparser** [comment]
Es decir, preparamos las latitudes de cada lugar, el mapica y la mecánica sería la misma pero en lugar de cargar html, cargamos el json para pasárselo a un template. Iba a pegar código directamente, pero ahora después de comer me pongo un rato y le echáis un vistazo si no. ¡Que aproveche!

**Comment by iblancasa** [comment]
Sí, claro. Se ahorra espacio y tal.
Si fue una solución un poco... "pachanguera", pero fue la más rápida que vi y sin armar un follón.

**Comment by stringparser** [comment]
Hahah, normal, si estamos todos liaos siempre. Pero para pachanguera, el mapica de te ha quedao muy chulo, de verdad :). 

Y el link de reactjs estaba mal, corregido.

**Comment by stringparser** [comment]
Te hago un fork ;)

**Comment by iblancasa** [comment]
> Pero para pachanguera, el mapica de te ha quedao muy chulo, de verdad :).

@stringparser Gracias :grin:

>Te hago un fork ;)

Sí, lo que quieras

**Comment by stringparser** [comment]
@iblancasa hay alguna manera de saber la latitud y longitud de una ciudad que no sea hardcodeando? La verdad es que no conozco la api de google maps. Voy mirar entre mientras por si las moscas.

**Comment by stringparser** [comment]
Esto de google maps esta chulo, en stackoverflow: 
 
 > http://stackoverflow.com/questions/3490622/get-latitude-and-longitude-based-on-location-name-with-google-autocomplete-api

**Comment by iblancasa** [comment]
En su momento estuve peleando con ello...
Es lo que te iba a postear.
Para Granada se haría una petición así:
http://maps.google.com/maps/api/geocode/json?address=Granada,Spain&sensor=false

Lo que pasa es que, con la pila de ciudades que tenemos, queriendo parsear los JSON y tal... ¿no serían demasiadas peticiones al servidor? No por el número de peticiones en sí, si no por la tardanza en la carga

**Comment by stringparser** [comment]
Si si, estoy contigo. Pero con hacerlas una vez basta. La latitud y longitud no cambia de un día para otro :dancer: hhahaah. Es decir, se guarda todo en un vector y listo :)

**Comment by iblancasa** [comment]
Creo que me estoy perdiendo.
¿Cómo lo quieres hacer? Si seguimos como yo lo tengo hecho (donde las páginas son estáticas de cara al servidor y es el cliente quien hacer todo el cómputo), eso creo que no se puede hacer ¿no? A menos que quieras usar el "LocalStorage".

Si lo hacemos como un servicio (con lo de Fiware y tal), si sería más factible. Es esto ¿no?

**Comment by stringparser** [comment]
Las páginas no serían estáticas, cada link cargaría json con una xhr a la api de github. Con código como este: 
```js
function get(jsonFile, callback){
  // see if we have it in cache first
  if(Cuidad[jsonFile]){
    return Ciudad[jsonFiile];
  }

  var xhr = new XMLHttpRequest();
  xhr.open('GET', dataURI + jsonFile + '?ref=gh-pages');
  xhr.setRequestHeader("Accept", "application/vnd.github.v3.raw+json");

  // errorrrrs, arrr!
  xhr.onerror = callback;
  xhr.onload = function(){
    callback(null, xhr.response, xhr);
    // ^ no error, give response and full xhr
  };

  xhr.send();
  // dispatch request (do not forget!)
}
```
y esto se iría agregando en una caché. 

LocalStorage sería interesante si, porque así no habría que preocuparse de que al refrescar la página la cache estuviera vacía de nuevo.

**Comment by stringparser** [comment]
Y estoy reutilizando tu código solo que en lugar de generar los archivos html de forma estática utilizamos los json para generar el html de forma dinámica.

**Comment by iblancasa** [comment]
No me refería a eso. Decía lo de obtener las coordenadas de las ciudades. Si lo haces en el navegador del cliente, vas a necesitar pedir todas las ciudades cada vez que cargues la web (a menos que, tras la primera carga, hayas guardado en el LocalStorage).

En cuanto a lo que planteas... ¿no sería más fácil hacerlo con JQuery como lo hacía yo? Ahorras código (creo). Estás pidiendo el fichero JSON que tendríamos subido al repo, ¿verdad?

Lo que no me termino de enterar... ¿lo quieres hacer en una página de estas de GitHub o como una aplicación aparte (como se habla en el #4 )?

**Comment by stringparser** [comment]
Déjame un poquito de rato más y te lo enseño. Si no te gusta, pues con lo que hay ya vale :) también. 

Las latitudes se hacen una vez y se incluyen con un script tag. Con una vez me refiero a un archivo, no a llamar a la api de google cada vez que se recarga la página :)

**Comment by iblancasa** [comment]
> Con una vez me refiero a un archivo

Ese dato es el que no pillaba. No entendía dónde querías guardarlo. Ya sí

**Comment by stringparser** [comment]
:+1:

**Comment by stringparser** [comment]
Falta poner las tablas y alguna ciudades que ha saltado el limite de petición en pontevedra. 
  [http://stringparser.github.io/gh-data-spain/](http://stringparser.github.io/gh-data-spain/)

Sólo hay iconos, voy a descansar un rato y luego pongo las tablas

**Comment by JJ** [comment]
Madre mía... qué artistas...

El 8 de febrero de 2015, 17:44, Javier Carrillo <notifications@github.com>
escribió:

> Falta poner las tablas y alguna ciudades que ha saltado el limite de
> petición en pontevedra.
> http://stringparser.github.io/gh-data-spain/
>
> Sólo hay iconos, voy a descansar un rato y luego pongo las tablas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-73418800>
> .
>



-- 
JJ

**Comment by JJ** [comment]
No están todas las ciudades... cada una hay que ver si necesita algún
filtro o configuración adicional.

El 8 de febrero de 2015, 17:48, JJ Merelo <jjmerelo@gmail.com> escribió:

> Madre mía... qué artistas...
>
> El 8 de febrero de 2015, 17:44, Javier Carrillo <notifications@github.com>
> escribió:
>
> Falta poner las tablas y alguna ciudades que ha saltado el limite de
>> petición en pontevedra.
>> http://stringparser.github.io/gh-data-spain/
>>
>> Sólo hay iconos, voy a descansar un rato y luego pongo las tablas
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-73418800>
>> .
>>
>
>
>
> --
> JJ
>



-- 
JJ

**Comment by stringparser** [comment]
hahaha, la idea del mapa es de @iblancasa, yo estoy refactorizando el código y metiendo cosas moernas :dancer:, poquito a poco. Y si, faltan ciudades porque [me ha saltado el límite de google maps](https://github.com/stringparser/gh-data-spain/blob/gh-pages/lib/spain-geo.js) (al final del archivo). 

Voy por el café.  Luego más tarde o después de cenar echo otro rato y pongo las listas de gente.

**Comment by JJ** [comment]
Sois unos putos cracks.

El 8 de febrero de 2015, 17:54, Javier Carrillo <notifications@github.com>
escribió:

> hahaha, la idea del mapa es de @iblancasa <https://github.com/iblancasa>,
> yo estoy refactorizando el código y metiendo cosas moernas [image:
> :dancer:], poquito a poco. Y si, faltan ciudades porque me ha saltado el
> límite de google maps
> <https://github.com/stringparser/gh-data-spain/blob/gh-pages/lib/spain-geo.js>
> (al final del archivo).
>
> Voy por el café. Luego más tarde o después de cenar echo otro rato y pongo
> las listas de gente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-73419280>
> .
>



-- 
JJ

**Comment by iblancasa** [comment]
@stringparser he visto que has comentado lo de "Ciudad Real" y "Las Palmas". Siento la chapuza, pero ahí @JJ no había arreglado lo de las ciudades con espacios en medio y yo estuve intentando hacerlo de algunas formas (como escpar el espacio al llamar al script que calcula el ranking cuando lo llamo desde el terminal), aunque no lo apañé.



> Sois unos putos cracks.

Se hace lo que se puede, aunque él me gana jajaja

**Comment by JJ** [comment]
Las puedes llamar simplemente con comillas. Si no, en un fichero de
configuracion como los que hay para muchas ciudades.

El 8 de febrero de 2015, 17:58, Israel Blancas <notifications@github.com>
escribió:

> @stringparser <https://github.com/stringparser> he visto que has
> comentado lo de "Ciudad Real" y "Las Palmas". Siento la chapuza, pero ahí
> @JJ <https://github.com/JJ> no había arreglado lo de las ciudades con
> espacios en medio y yo estuve intentando hacerlo de algunas formas (como
> escpar el espacio al llamar al script que calcula el ranking cuando lo
> llamo desde el terminal), aunque no lo apañé.
>
> Sois unos putos cracks.
>
> Se hace lo que se puede, aunque él me gana jajaja
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-73419514>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
hahahaha, tu si que eres un Chamán @JJ

Ahhh, ¿eso era? Ciudad Real y Las Palmas... ¡Ok! Ahora mismo lo pongo con guiones y a unas malas se cambian a la hora de verdad los guiones por espacio. De todas formas tendré que hacer un mapeo entre nombres máquina y los normales, humanos y naturales :)

**Comment by stringparser** [comment]
Hecho. Lo dicho, voy a dar una vuelta que me de este sol frío en mi cara blanca y pillarme un café o algo. Ya me contais, luego hablamos :)

**Comment by stringparser** [comment]
Y 
> @iblancasa Sois unos putos cracks.
> Se hace lo que se puede, aunque él me gana jajaja

Nehh, más viejo y pellejo :D pero solo eso

**Comment by stringparser** [comment]
Y... vamos a cenar: 

http://stringparser.github.io/gh-data-spain/

tiene unos cuantos bugs: 
 - Los nombres de los archivos no pueden tener letras que no se puedan codificar en la url y falla al cargar
 -  El tamaño de la tabla ha de ser ajustable porque cuando se hace la pantalla más pequeña no entra. 
 - Y más cosas seguro que no tengo ni idea :smile: 

Cualquier cosa, decidme. Y lo dicho al principio, si esto no es el camino a seguir se va por otro lao que no me importa ;)

**Comment by stringparser** [comment]
Y ya para la cama. Ale, buenas noches ;)

http://github-users-grx.github.io/gh-data-spain

**Comment by iblancasa** [comment]
Buen trabajo.
Cuando acabe los exámenes me pongo y hago alguna cosilla (si se me ocurre algo y si sé hacerlo, claro jajja)

**Comment by stringparser** [comment]
Hahaha, gracias tío y suerte con los exámenes. Tu pregunta si no, que no es tan difícil :). Buenas noches.

**Comment by iblancasa** [comment]
Gracias, la necesito jajajaja :sweat_smile:

**Comment by stringparser** [comment]
:+1: y :8ball:!

**Comment by JJ** [comment]
:-)

2015-02-09 0:35 GMT+01:00 Javier Carrillo <notifications@github.com>:

> [image: :+1:] y [image: :8ball:]!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-73439717>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
@JJ, estaba pensando en poner esto al día. Ponemos la web en este repo y usamos los datos que tu vayas sacando? o la dejamos en la org y usamos los datos de aqui? Lo digo para que siempre estén actualizados

**Comment by stringparser** [comment]
Me explico fatal ahahah. Lo quiero decir es usar directamente lo que vas sacando en este repositorio en lugar de mantener una copia

**Comment by JJ** [comment]
Me parece bien.

2015-04-07 13:16 GMT+02:00 Javier Carrillo <notifications@github.com>:

> Me explico fatal ahahah. Lo quiero decir es usar directamente lo que vas
> sacando en este repositorio en lugar de mantener una copia
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-90509399>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
Ok, perfect. Estaba probando y con la dirección de abajo se puede sacar el json
https://api.github.com/repos/JJ/top-github-users-data/contents/data/user-data-Almer%C3%ADa.json

¿Te mando cuando buenamente pueda una PR para [cambiar la branch gh-pages de este repo](http://jj.github.io/top-github-users-data/) o lo mantenemos donde está haciendo las llamadas aquí? Si es lo primero estaba pensando en mantener el diseño como está cambiando la lista que hay debajo de "Provincias (y otros)" y poner el mapa ahí.

**Comment by stringparser** [comment]
En verdad cambiar la gh-pages, aunque la idea es sencilla, llevarla a cabo tiene bastante curro. Así que no se muy bien que hacer.

**Comment by JJ** [comment]
¿Lo que quieres es simplemente cambiar el enlace?

**Comment by stringparser** [comment]
Hostia, cambiar el enlace sería otra opción. La contrapartida sería que los documentos que tienes aquí ya hechos con la lista de cada cuidad no se verían al hacer click, sino que te llevaría al mapa. Si es algo que quieres quitarte del medio (generar los md para cada cuidad) podría ser una solución.

Lo que quería era poner el mapa en lugar de la lista con las ciudades, pero tiene bastante curro porque habría que cambiar como se renderiza todo en las gh-pages que tienes aquí. No se, ¿lo hago simple y sólo actualizo el enlace para que use los datos de aquí en http://github-users-grx.github.io/gh-data-spain?

**Comment by JJ** [comment]
Como veas. Otra opción también es usar CartoDB, que tiene API y se pueden hacer muchas cosas con él.

**Comment by Nesta** [comment]
Buenas! gran idea esto :) no lo había visto hasta ahora y me ha molado mucho.

Mirando las issues por si podía solucionar alguna o comentar o algo he encontrado esto.

Me parece una idea perfecta en tener una web y hacer esto un poco más dinámico en tema de ciudades y fecha actual.

No se en que ha quedado el tema, me leeré todo lo que haya por aqui escrito y si necesitáis apoyo será un placer ayudar!

Gracias!

**Comment by JJ** [comment]
¡Gracias!

**Comment by stringparser** [comment]
@Nesta yo estoy intentado utilizar este repo para tener los listado actualizados conforme @JJ tenga nuevos datos. Pero se podría hacer algo más curioso y tener una web pequeña para que la gente tenga donde comentar. Con [disqus](https://disqus.com/) por ejemplo se podría acompañar el contenido a las gh-pages.

**Comment by stringparser** [comment]
Estoy va tomando forma :). Ciudades y listas por fin funcionan con los últimos datos que tienes aquí @JJ. 

![image](https://cloud.githubusercontent.com/assets/7457705/7796789/795608c4-02e3-11e5-91ff-7ddc5329911a.png)

Al hacer click en la fila lleva al perfil de github. La tabla aparece al hacer click en alguno de los octogaticos. Se quita dándole a escape por el momento. Ahora después le pondré un botón para cerrarlo. 

![image](https://cloud.githubusercontent.com/assets/7457705/7796773/4bc95a0a-02e3-11e5-9201-0308676a784d.png)

Arriba como veis he dejado preparadas algunas secciones más. 

- blog: para resaltar lo que se haga. 
- meetups: se rellenarían automáticamente con los issues que dejes aquí escritos @JJ 
- proyectos: una pestaña donde hacer showcase de cosas que se hagan o que la gente quiera promover

La idea que tengo es que, excepto las meetups y el maña que se rellenan automáticamente, para incluir más contenido se haga una PR con un documento markdown (o kramdown, trabajando en eso también) y así se actualice el contenido sin mucha complicación.

Cualquier cosa que veáis sería interesante añadir o mejorar comentadlo ;)

**Comment by stringparser** [comment]
Jajaja, he escrito proyectos con jota (véase cualquiera de los dos screenshots :smile:)

**Comment by iblancasa** [comment]
@stringparser eso te iba a decir jajajajaj.
Mola mucho :dancer:

**Comment by stringparser** [comment]
@iblancasa gracias! :smile:

**Comment by JJ** [comment]
Oye, como mola!

2015-05-25 14:29 GMT+02:00 Javier Carrillo <notifications@github.com>:

> @iblancasa <https://github.com/iblancasa> gracias! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-105225165>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
@JJ que bien! A ver si esta semana la dejo funcionando :)

**Comment by stringparser** [comment]
Alpha 
http://github-users-grx.github.io

**Comment by stringparser** [comment]
ßeta! 

Hay algun que otro bug y cosas que mejorar pero está funcionando :)
http://github-users-grx.github.io/

Página inicial: 
![image](https://cloud.githubusercontent.com/assets/7457705/7916934/32586008-0887-11e5-97ac-0ae027ba2d9c.png)

Blog: 
![image](https://cloud.githubusercontent.com/assets/7457705/7916950/441363ec-0887-11e5-9215-801d7e8e108b.png)

Post: pueden tener LaTex y se escriben en kramdown.
![image](https://cloud.githubusercontent.com/assets/7457705/7917037/bafd3906-0887-11e5-94a5-f451870e2c9a.png)

Proyectos: 
![image](https://cloud.githubusercontent.com/assets/7457705/7916963/531439c0-0887-11e5-85d7-f762edaabe49.png)

Detalle del proyecto: 
![image](https://cloud.githubusercontent.com/assets/7457705/7917046/ced2c2c0-0887-11e5-8b33-51c3e7c0d3bf.png)

-----

El link del chat lleva a gitter y el link de meetups a este repositorio. Estuve pensándolo y de poner las meetups ahí se pederían las notificaciones o habría que hacer algo extra para notificar y aquí en github ya las tenemos. 

Y eso, cualquier crítica es bienvenida :).

**Comment by JJ** [comment]
A difundir... queda genial

El 1 de junio de 2015, 18:01, Javier Carrillo <notifications@github.com>
escribió:

> ßeta!
>
> Hay algun que otro bug y cosas que mejorar pero está funcionando :)
> http://github-users-grx.github.io/
>
> Página inicial:
> [image: image]
> <https://cloud.githubusercontent.com/assets/7457705/7916934/32586008-0887-11e5-97ac-0ae027ba2d9c.png>
>
> Blog:
> [image: image]
> <https://cloud.githubusercontent.com/assets/7457705/7916950/441363ec-0887-11e5-9215-801d7e8e108b.png>
>
> Post: pueden tener LaTex y se escriben en kramdown.
> [image: image]
> <https://cloud.githubusercontent.com/assets/7457705/7917037/bafd3906-0887-11e5-94a5-f451870e2c9a.png>
>
> Proyectos:
> [image: image]
> <https://cloud.githubusercontent.com/assets/7457705/7916963/531439c0-0887-11e5-85d7-f762edaabe49.png>
>
> Detalle del proyecto:
> [image: image]
> <https://cloud.githubusercontent.com/assets/7457705/7917046/ced2c2c0-0887-11e5-8b33-51c3e7c0d3bf.png>
> ------------------------------
>
> El link del chat lleva a gitter y el link de meetups a este repositorio.
> Estuve pensándolo y de poner las meetups ahí se pederían las notificaciones
> o habría que hacer algo extra para notificar y aquí en github ya las
> tenemos.
>
> Y eso, cualquier crítica es bienvenida :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/13#issuecomment-107607682>
> .
>



-- 
JJ

**Comment by RDCH106** [comment]
@stringparser @iblancasa @JJ 
Una idea interesante!!

Pero no puedo acceder a http://github-users-grx.github.io
¿Dónde puedo encontrar el código para echarle un ojo?
