### ISSUE TITLE
When equal number of contibutions order by followers?

### ISSUE THREAD

**Issue by javacasm** [JJ/top-github-users-data#14]
When two users have equal number of contibutions, order by followers number? order by stars?
You can check at myself: with 334 contributions ahead a 85 stars user....

**Comment by JJ** [comment]
Could be, yes...

2015-02-09 22:14 GMT+01:00 Jose Antonio Vacas <notifications@github.com>:

> When two users have equal number of contibutions, order by followers
> number? order by stars?
> You can check at myself: with 334 contributions ahead a 85 stars user....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/14>.
>



-- 
JJ
