### ISSUE TITLE
Mejorar la apariencia de las tablas

### ISSUE THREAD

**Issue by potray** [JJ/top-github-users-data#15]
Sería interesante mejorar la estética de las tablas haciendo que no se alarguen las imágenes de los perfiles de las personas, y que éstas aparezcan cuadradas. Una posible solución es hacer más estrecha la columna "Contribuciones" como se puede apreciar aquí: https://github.com/potray/top-github-users-data/blob/master/formatted/top-C%C3%A1ceres.md

**Comment by JJ** [comment]
La plantilla está en https://github.com/JJ/github-city-rankings/tree/master/layout Si te animas...

**Comment by potray** [comment]
He hecho un pull request :smile:

**Comment by JJ** [comment]
Y yo lo he aceptado :-)
