### ISSUE TITLE
Github meetup #3: March 6th 2015

### ISSUE THREAD

**Issue by JJ** [JJ/top-github-users-data#17]
Where
--------

March 6, 7:00 PM, Sala Generalife, [CEVUG](http://cevug.ugr.es) C/ Real de Cartuja, 36-38 Granada. We can no longer fit in the OSL.

What
------

* General introduction to the @github crowd in Granada
* Intro to socket.io by @iblancasa
* Local craft beer at El Sur de Granada

Who
-----

Everyone is invited, whether you are in @github or not, but specially @stringparser, @iblancasa, @fergunet, @rafael1193, @psicobyte, @renatolrr, @makova, @fdavidcl, @ncordon, @m42, @eparejatobes, @pablopareja, @vterron, @pleonex, @ernestoalejo, @oskyar, @oxcar103, @algui91, @potray, @antorof, @fergunet, @demiurgosoft, @rafael1193, @unintendedbear, @agarciamontoro, @torresj, @josemlp91, @juanafernandez @ivanortegaalba @pbaeyens  y @franexposito.

Why
--------

We githubbers will be meeting every first Friday of every month, at the @oslugr or anywhere for technical and trash talking. We'll do it in Spanish or English, depending on what language is the best for all parties involved. This issue closes #12 .

**Comment by JJ** [comment]
I can ask for a guest Wifi account if needed.

**Comment by stringparser** [comment]
Niiice :space_invader: :D  

Just in case, here is [how the cevugr building looks like][x-cevugr]. And to get there you can go by: 
  - Bus
     - Find you way with the [GranadaBus app][x-bus], or
     - Get lucky finding the bus name you need on the [robert map][x-rober]
  - Foot. If you know were [Triunfo][x-triunfo] is, follow the dots :dancers:. 

And here is where the [`Sala Generalife` is within the building][x-sala] 

[x-cevugr]: http://cevug.ugr.es/donde-estamos.html
[x-rober]: http://www.granadadirect.com/transporte/lineas-autobuses-granada
[x-bus]: https://play.google.com/store/apps/details?id=org.granada.bus&hl=es
[x-sala]: http://cevug.ugr.es/infraestructura/infra/sala-reuniones-videoconferencia.html
[x-triunfo]: https://www.google.es/maps/dir/Calle+Real+de+Cartuja,+36,+Granada/37.1834828,-3.6028642/@37.1834563,-3.6022223,230m/data=!3m1!1e3!4m14!4m13!1m10!1m1!1s0xd71fcc25f5f2c23:0xb7f89669913ec929!2m2!1d-3.5999955!2d37.186503!3m4!1m2!1d-3.6018712!2d37.1831582!3s0xd71fcea06587fd1:0xf39ff4e12ae9159d!1m0!3e2

**Comment by iblancasa** [comment]
Car is not a good idea :oncoming_automobile:

**Comment by unintendedbear** [comment]
See you there! I hope I have time to make mini-cupcakes :cake: :)

**Comment by juanAFernandez** [comment]
Cool!

**Comment by ivanortegaalba** [comment]
:+1:

**Comment by juanAFernandez** [comment]
At the end, i have to go to my village and i can't take part, sorry :(.
Have fun!

**Comment by stringparser** [comment]
Me too, its been a while since I was there, enjoy!

**Comment by JJ** [comment]
Muchachos, no os perdáis el próximo. Si no hay más crónicas o fotos que subir cierro.
