### ISSUE TITLE
Improved location

### ISSUE THREAD

**Issue by vrruiz** [JJ/top-github-users-data#18]
The location method of searching only big cities and province names leaves out users who live in smaller places. INE has the complete list of towns in Spain, so a search can be done at least once to try to locate those http://www.ine.es/daco/daco42/codmun/codmun11/11codmun.xls

Next improvement is to do location sanity with the returned users using Yahoo Geo API, or other similar ones like Thomson API, which support fuzzy logic to distinguish between "Toledo, USA" and "Toledo, España".

**Comment by JJ** [comment]
In fact, I filter that, but if somebody just says "Toledo" it's impossible to know. That happens with Guadalajara, where I have eventually abandoned any attempt at filtering. I don't think it happens much with the rest, but it might. 
In general, also, people in smaller places tend to be residual. There might be some, but not many. Even big cities like Algeciras or Gijón add only 5% to the total, just check out thos provinces. 
If we include every single toponym that would be lots of GitHub API requests (and they are limited) and I don't really think they would actually add much to what it''s there.
