### ISSUE TITLE
Github meetup #4: April 17th 2015

### ISSUE THREAD

**Issue by M42** [JJ/top-github-users-data#21]
## Where

April 17, 7:00 PM, Sala Generalife, CEVUGR.
C/Real de Cartuja 36-38, Granada.

## What

For this meetup, @JJ asked @pbaeyens and me to explain an introduction to the **Haskell programming language**. We will talk about functional programming, mathematical reasoning and examples of Haskell code.

## Who

As always, everyone is invited.
@stringparser, @iblancasa, @fergunet, @rafael1193, @psicobyte, @renatolrr, @makova, @fdavidcl, @ncordon, @eparejatobes, @pablopareja, @vterron, @pleonex, @ernestoalejo, @oskyar, @oxcar103, @algui91, @potray, @antorof, @fergunet, @demiurgosoft, @rafael1193, @unintendedbear, @agarciamontoro, @torresj, @josemlp91, @juanafernandez @ivanortegaalba @franexposito @elenamerelo @rosanamontes @nuriastatgirl @rogegg

**Comment by JJ** [comment]
Room is confirmed.

**Comment by JJ** [comment]
Also @elenamerelo @unintendedbear @rosanamontes @nuriastatgirl @rogegg and the rest!

**Comment by vterron** [comment]
+1

**Comment by JJ** [comment]
¿@vterron vendrás o andas ya por tierras bárbaras?

**Comment by agarciamontoro** [comment]
¡Guardadme un sitio en primera fila!

**Comment by stringparser** [comment]
hostiarrrr, haskell! +1

**Comment by juanAFernandez** [comment]
:)

*Juan Antonio Fernández Sánchez*
*E.T.S. de Ingenierías Informática y de Telecomunicación | Universidad de
Granada*
*Correo: *juan.antonio.fernandez.sanchez.88@gmail.com | *Tfno*: 677164459
<https://webmailest.ugr.es/?_task=mail&_action=show&_uid=1933&_mbox=INBOX&_search=b73a064aeb6f163755601057b110b2bd>

2015-03-24 15:45 GMT+01:00 Javier Carrillo <notifications@github.com>:

**Comment by renatolrr** [comment]
Wonderful (Mola)

**Comment by ivanortegaalba** [comment]
Vaya pros que se mueven por el Github meetup! +1 of course!

**Comment by oxcar103** [comment]
Quizás les interese a @Lothar94 y @jopime

**Comment by iblancasa** [comment]
No sé si podré ir. Es mi cumpleaños y, tal vez, venga la familia

**Comment by analca3** [comment]
Allí estaré ;-D!

**Comment by makixun** [comment]
Puedo asistir? ;)

**Comment by psicobyte** [comment]
No, tú no puedes asistir. :P

**Comment by makixun** [comment]
xDD

**Comment by JJ** [comment]
Tendremos pegatinas.

**Comment by josejuansanchez** [comment]
¿Os habéis planteado la posibilidad de hacer un streaming por Hangout o similar para que os podamos seguir los que no estamos en Granada? Estaría genial! :)

**Comment by JJ** [comment]
Podemos intentarlo...

JJ

**Comment by josejuansanchez** [comment]
@JJ ¡Genial! Contad conmigo para seguiros desde Almería.

**Comment by eparejatobes** [comment]
hi everyone! that sounds like category theory, so count me in :+1: 

@laughedelic ?

**Comment by laughedelic** [comment]
Sounds to me like lambdas all the way down, so count me in too! :ok_hand:

**Comment by demiurgosoft** [comment]
i'll try to be there this time

**Comment by Makova** [comment]
👍

**Comment by stringparser** [comment]
There are some friend's friends playing on Polaroid tomorrow and they are talking about meeting before, so I might not go at the end... I'm trying to change it to this Sunday. Lets see if I can do that.

**Comment by JJ** [comment]
You'll be missed. Or not.

**Comment by stringparser** [comment]
@JJ hahaha. I'll be there tomorrow λs!

**Comment by JJ** [comment]
¿Fotos? ¿Enlace a la presentación? ¿Comentarios? El último que cierre el issue.

**Comment by M42** [comment]
Enlaces a la presentación [en 4:3](https://github.com/M42/osl-talk-haskell/raw/master/pdfs/sin_notas.pdf) y [en 16:9](https://github.com/M42/osl-talk-haskell/raw/master/pdfs/169.pdf).

**Comment by stringparser** [comment]
¡Gracias! Dejo aquí también vuestro repo: https://github.com/github-users-grx/osl-talk-haskell

**Comment by analca3** [comment]
Dejo como curiosidad lo que os comenté a algunos sobre lenguajes como armas XD.

http://bjorn.tipling.com/if-programming-languages-were-weapons

**Comment by JJ** [comment]
Convocada la siguiente para el 22 de mayo, con @eparejatobes hablando de Scala: #24 
Trataré de pedir pegatinas...
