### ISSUE TITLE
GithubMining

### ISSUE THREAD

**Issue by stringparser** [JJ/top-github-users-data#22]
Como te lo perdiste esta mañana te lo dejo por aquí. Es parte de la presentación que dio @fcharte.

https://github.com/fcharte/GitHubMining

**Comment by JJ** [comment]
Gracias (y también a @fcharte)

2015-03-25 19:15 GMT+01:00 Javier Carrillo <notifications@github.com>:

> Como te lo perdiste esta mañana te lo dejo por aquí. Es parte de la
> presentación que dio @fcharte <https://github.com/fcharte>.
>
> https://github.com/fcharte/GitHubMining
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/22>.
>



-- 
JJ

**Comment by stringparser** [comment]
Te cierro este, que ya hace de esto :)
