### ISSUE TITLE
Discordancia de datos

### ISSUE THREAD

**Issue by luismagr** [JJ/top-github-users-data#23]
Hola,

Me ha dado por buscarme tanto en Cádiz como en Andalucía y aparezco mejor posicionado en Andalucía. Me resulta extraño que si estoy por el 42 en Cádiz aparezca como el 18 en Andalucía.

Viendo el comentario del commit asociado a la última modificación del fichero de Cádiz ("Adds Extremadura plus aggregated") ¿Puede ser que se hayan metido ahí a la gente de Extremadura?

El caso es que en Andalucía debería aparecer mínimo en la misma posición o si acaso en una posición con un número mayor

**Comment by JJ** [comment]
El top de Andalucía tiene sólo aquellos que tienen esa palabra en el perfil
(muy pocos). El
https://github.com/JJ/top-github-users-data/blob/master/formatted/top-alt-Andaluc%C3%ADa.md
el que incluye, además, a todos los de las provincias.

En todo caso, se descargan en diferentes días. Podría haber alguna
diferencia.

**Comment by JJ** [comment]
En el de toda Andalucía (incluyendo provincias) estás el 554 https://github.com/JJ/top-github-users-data/blob/master/formatted/top-alt-Andaluc%C3%ADa.md

**Comment by luismagr** [comment]
Ya decía yo... Esto sí me encaja. Muchas gracias
