### ISSUE TITLE
Github meetup #5: May 22th.

### ISSUE THREAD

**Issue by JJ** [JJ/top-github-users-data#24]
Esta vez será @eparejatobes quien nos hablará de Scala. 7 de la tarde, como es habitual, en la sala Generalife del CEVUG, encima de la Oficina de software libre.
¿Quień se apunta? Como siempre, todos estáis invitados

@stringparser, @iblancasa, @fergunet, @rafael1193, @psicobyte, @renatolrr, @makova, @fdavidcl, @ncordon, @eparejatobes, @pablopareja, @vterron, @pleonex, @ernestoalejo, @oskyar, @oxcar103, @algui91, @potray, @antorof, @fergunet, @demiurgosoft, @rafael1193, @unintendedbear, @agarciamontoro, @torresj, @josemlp91, @juanafernandez @ivanortegaalba @franexposito @elenamerelo @rosanamontes @nuriastatgirl @rogegg @analca3 @fcharte

**Comment by analca3** [comment]
No debería de tener problemas ese finde, así que allí estaré!

**Comment by Makova** [comment]
Esta vez no falto.

El 9 de mayo de 2015, 13:41, Antonio Álvarez <notifications@github.com>
escribió:

> No debería de tener problemas ese finde, así que allí estaré!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/24#issuecomment-100467883>
> .
>



-- 
Manu

**Comment by makixun** [comment]
No faltaré.

**Comment by unintendedbear** [comment]
Ju, yo estoy en Madrid el 22 :_(

**Comment by stringparser** [comment]
Cawen! yo si estoy por Graná. Allí nos vemos.

**Comment by JJ** [comment]
Ya queda menos ¿no? ¿Quién más viene?

**Comment by ivanortegaalba** [comment]
:( yo estoy en la DrupalCamp...

**Comment by agarciamontoro** [comment]
¡Allí estaré!

**Comment by M42** [comment]
Yo también. Imagino que a @pbaeyens también le interesará. Y seguro que acabaremos siendo unos cuantos del doble grado.

**Comment by fdavidcl** [comment]
Contad conmigo! :octocat:

**Comment by oxcar103** [comment]
Yo :octocat:

**Comment by iblancasa** [comment]
Yo si voy será más tarde... tengo clase de inglés y es la última antes del examen :S

**Comment by analca3** [comment]
Al final tengo que volver al pueblo, así que no podré ir :((. ¡Pero veré la presentación cuando la colguéis!

**Comment by eparejatobes** [comment]
Hola a todos! vamos @laughedelic y yo. La idea es contar un poco del lenguaje en general, y luego ver algo de código real con bases de datos de grafos.

**Comment by JJ** [comment]
¡Genial!
Yo tampoco puedo ir, pero os agradecería que pusiérais las transpas.

**Comment by eparejatobes** [comment]
Los que llevéis ordenador estaría bien tener [sbt](http://www.scala-sbt.org/) instalado. Si alguno tiene algún problema, estaré por allí un rato antes!

**Comment by eparejatobes** [comment]
@JJ seguro, mañana pongo el código y las slides :+1:

**Comment by stringparser** [comment]
Ok, instalo sbt ;)
