### ISSUE TITLE
Etiquetar las meetups

### ISSUE THREAD

**Issue by stringparser** [JJ/top-github-users-data#25]
@JJ estoy haciendo una web más completita con los datos que tienes aquí para hospedarla en la org que hiciste de Graná :). 

Tengo un par de ideas y aunque no quiero complicarlo estaba pensando que si los issues de las meetups estuvieran etiquetados se podría filtrar los resultados de https://api.github.com/repos/JJ/top-github-users-data/issues, con las labels y no tener que mover un dedo a la hora de publicarlo tanto aquí como en la web.

**Comment by stringparser** [comment]
Aquí va como llevo el diseño con el mapa. 

![mockup](http://snag.gy/JAfFC.jpg)

Donde pone "hello nigger" :smile: es donde aparecería la lista en cada provincia.

**Comment by iblancasa** [comment]
Ni una triste mención, que lo del mapa lo moví yo aquí (aunque estaba más pachanguerete) http://iblancasa.com/top-github-users-data-spain/ (rama gh-pages de aquí https://github.com/iblancasa/top-github-users-data-spain)

Que poco me queréis... :disappointed_relieved:

**Comment by stringparser** [comment]
Hay, perdón. Ahora te pongo

**Comment by iblancasa** [comment]
Que no pasa ná JAJAJAAJ Que es bromaa

**Comment by stringparser** [comment]
jajja, sera broma pero tienes razón :)

**Comment by stringparser** [comment]
No va a hacer falta etiquetar los issues de las quedadas. Voy a usar los títulos que tienen un formato consistente.  

![image](https://cloud.githubusercontent.com/assets/7457705/7736446/13a89264-ff44-11e4-883e-23be2fa8f91b.png)

Cierro este.
