### ISSUE TITLE
gitter?

### ISSUE THREAD

**Issue by eparejatobes** [JJ/top-github-users-data#26]
Creo que estaría bien tener un room para el repo (discutir próximos/pasados meetups, dudas, organizar cosas...)

**Comment by eparejatobes** [comment]
El link: https://gitter.im/

**Comment by JJ** [comment]
De hecho, hay uno: https://gitter.im/github-users-grx

**Comment by stringparser** [comment]
Si, ese es sólo para la gente de la org y el público https://gitter.im/github-users-grx/changelog
