### ISSUE TITLE
Code in R data processors to include them in reports

### ISSUE THREAD

**Issue by JJ** [JJ/top-github-users-data#28]
Right now you have to run a Perl script in advance.

**Comment by iblancasa** [comment]
I was trying to do something similar here
https://github.com/iblancasa/GitHub-DataProcessor-Spain

**Comment by JJ** [comment]
That's cool. I've never tried R to that level...

**Comment by JJ** [comment]
I mean, you doing it is cool. R OO programming is downright ugly.

**Comment by iblancasa** [comment]
Hahaha, I was trying to make it more easy to use. 

To show data each week (to do more things with data)
http://spanish-data.iblancasa.com/

I created it in Python but then, I changed it to R. Now this website is not correct because I was using another "format"
