### ISSUE TITLE
Actualizaciones andalucía. Añadir Cádiz

### ISSUE THREAD

**Issue by Foxandxss** [JJ/top-github-users-data#29]
Por alguna razón, cuando actualizas Andalucía, no añades Cádiz.

Yo por ejemplo no salgo en el top-andalucía (en formatted).

**Comment by JJ** [comment]
El problema es que las actualizaciones están fallando últimamente, porque devuelve errores GitHub. Las vuelvo a lanzar a mano a veces, pero creo que va a haber que reprogramarlo todo.

**Comment by Foxandxss** [comment]
Ya veo. Gracias por el trabajo, me gusta mucho este repo y lo visito a menudo.

**Comment by JuanLuisGarciaBorrego** [comment]
Yo tampoco salgo en Andalucía, he actualizado mi localización de perfil a [localidad, Provincia, Comunidad, Spain]

**Comment by JJ** [comment]
¿Cuando lo actualizaste?
Por cierto, el problema de Cádiz venía del API, pero ya lo solucioné. La última actualización debería ser de ayer.

**Comment by JuanLuisGarciaBorrego** [comment]
Ayer lo actualicé (para que la próxima vaya to bien).
Gracias

**Comment by Foxandxss** [comment]
En la última actualización sigue sin aparecer cádiz.

**Comment by JJ** [comment]
Lo miraré. Gracias por avisar.

**Comment by JJ** [comment]
Se actualizó el lunes pasado. ¿Cuál es el problema? En Top-Andalucía aparecen sólo los que tienen "Andalucía" en el perfil. Top-alt-Andalucía es el que incluye todas las provincias. https://github.com/JJ/top-github-users-data/blob/master/formatted/top-alt-Andaluc%C3%ADa.md
Si no os importa, cierro
