### ISSUE TITLE
Actualización Granada

### ISSUE THREAD

**Issue by algui91** [JJ/top-github-users-data#30]
Me he fijado que hace 23 días que no se actualiza el ranking para Granada. Normalmente se actualizaba todos los Lunes. Ha fallado algo o se ha cambiado la frecuencia de actualización?

**Comment by JJ** [comment]
Actualizando...

**Comment by algui91** [comment]
Perfecto!, qué había pasado?

On Wed, Jan 13, 2016, 17:44 Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> Actualizando...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/30#issuecomment-171359092>
> .
>
-- 

Alejandro Alcalde - elbauldelprogramador.com

**Comment by JJ** [comment]
Simplemente que el ordenador desde el que se hace no estaba encendido.

2016-01-13 17:50 GMT+01:00 Alejandro Alcalde <notifications@github.com>:

> Perfecto!, qué había pasado?
>
> On Wed, Jan 13, 2016, 17:44 Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
>
> > Actualizando...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/JJ/top-github-users-data/issues/30#issuecomment-171359092
> >
> > .
> >
> --
>
> Alejandro Alcalde - elbauldelprogramador.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/30#issuecomment-171361153>
> .
>



-- 
JJ

**Comment by algui91** [comment]
Jaja, algo importante para actualizar. Saludos!. Me meto todos los lunes para ver cómo va el ranking :-)

**Comment by JJ** [comment]
Estará en un rato, está ahora mismo bajándoselo todo.

**Comment by JJ** [comment]
Ya actualizado :-)

**Comment by algui91** [comment]
Sí, ya ví, en sigo en el mismo puesto en Granada. Cuando pueda hacer públicos los repos que tengo privados... subiré! jjaja

**Comment by JJ** [comment]
Pues no sé a qué esperas :-)

**Comment by algui91** [comment]
A que acabe el cuatrimestre xD

**Comment by algui91** [comment]
Parece que el ordenador encargado de actualizar vuelve a estar apagado @JJ  :-)

**Comment by JJ** [comment]
No, es que debe haber habido algún problema con github esta mañana.
Rehaciendo.

**Comment by algui91** [comment]
Gracias!

On Mon, Feb 15, 2016 at 5:13 PM Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> No, es que debe haber habido algún problema con github esta mañana.
> Rehaciendo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/30#issuecomment-184276435>
> .
>
-- 

Alejandro Alcalde - elbauldelprogramador.com
