### ISSUE TITLE
Update data from Baleares

### ISSUE THREAD

**Issue by alvaromb** [JJ/top-github-users-data#32]
😊

**Comment by alvaromb** [comment]
Ping @JJ!

Please let me know if you need help :)

**Comment by Nekmo** [comment]
Entire repository takes months outdated :(

**Comment by Beelzenef** [comment]
I think this project is not alive anymore, @Nekmo

**Comment by jsanchezgr** [comment]
As far as I know, the project is no longer updated since the private contributions compute in the stats.

**Comment by JJ** [comment]
It's not really dead. It's undead, rather. It was not updated since Github
added private-repo contributions, but now they can be eliminated, so I
might rewrite the scraping part, which, BTW, is in another repo,
github-city-rankings.

**Comment by iblancasa** [comment]
Hi @alvaromb @Nekmo @Beelzenef @jsanchezgr
https://github.com/iblancasa/ghrankings/blob/master/baleares.md

**Comment by jsanchezgr** [comment]
@iblancasa great, thank you!
