### ISSUE TITLE
Top Granada

### ISSUE THREAD

**Issue by algui91** [JJ/top-github-users-data#33]
Hola, ya no se sigue actualizando?

Saludos!

**Comment by JJ** [comment]
Lo dejé de actualizar cuando empezaron a contabilizar contribuciones a repo
privados. Dejó de tener gracia. Lo podría actualizar, aunque fuera para
contar usuarios.

**Comment by algui91** [comment]
Ah, ok. Nah, si ya no tiene gracia déjalo.
