### ISSUE TITLE
¿Actualizar esto lleva demasiado trabajo? 👀

### ISSUE THREAD

**Issue by rosepac** [JJ/top-github-users-data#35]
Desconozco si el flujo es muy complejo... Existe otra lista, de España, pero creo que también se paralizo su actualización..
👉 http://www.githubstats.com/country/spain/0/25?

A mi me gustaría ponerlos en marcha, si no llevase demasiada labor.. ¿Un poco de info rápido? 🙈

**Comment by JJ** [comment]
Hola, Pablo. Pues habría que reprogramarlo entero, y de hecho eso fue lo
que hizo @iblancasa/ghrankings
<reply@reply.github.com>
durante un tiempo, hasta que dejó de hacerlo... Es cuestión de usar el API
de GitHub en el lenguaje que quieras, quizás lo mejor sea empezar desde
cero...

**Comment by iblancasa** [comment]
El problema "gordo" es que GitHub cambia continuamente el frontend de la página de perfiles... y eso hace que sea muy pesado el mantenerlo. Por no hablar de ir "peleando" contra los bloqueos de IP y errores que la página devuelve de forma aleatoria... Además, hay que tener en cuenta la diferencia entre publicaciones públicas y privadas y eso ya... dispara todo.

Otra opción sería usar esto: https://www.gharchive.org/

**Comment by mdelapenya** [comment]
Existe otro servicio creo que más activo: https://commits.top/spain_private.html

**Comment by rosepac** [comment]
@JJ @iblancasa @mdelapenya Gracias por responder. Si es tan lioso como suponía, casi mejor que no. Mejor dedicar el tiempo a otras cositas..

 Seguramente, es más fácil editar `commits.top\` como indica @mdelapenya.

Gracias por responder. Saludos 🍻✊
