### ISSUE TITLE
Añadir un dato de commit desde el anterior ranking

### ISSUE THREAD

**Issue by javacasm** [JJ/top-github-users-data#4]
Añadir un dato de numero de commits en la última semana o desde le anterior ranking
Así se ve quien curra y quien vive de las rentas ;)

**Comment by pleonex** [comment]
Más simple: sacarlo parseando el HTML del perfil que se pide para sacar los commits anuales. En la parte de abajo, *Contribution activity*, por defecto sale el número de *actividades* de la última semana.

Si se quiere ver en otro periodo de tiempo, se tiene que añadir en las *queries* de la URL, el valor `period=XX`, donde XX he visto que puede valer
* weekly: última semana
* daily: último día
* halfweekly: últimos 3 días
* monthly: último mes

Desde un día particular con `from=año-mes-día` o incluso se pueden periodos añadiendo un `to=año-mes-día`.

Si se toma que la lista se actualiza semanalmente, sería sencillo saber tanto los commits de la última semana (viene en *Contribution activity*), como la lista de la semana pasada (restando los commits de esta semana) para añadir si se sube o baja de puesto.

**Comment by JJ** [comment]
@pleonex igual podríamos hacer eso, actualizar la lista semanalmente. Lo pongo alto en el TODO.

**Comment by stringparser** [comment]
Hostia, eso valdría para el webservice del que hablas en el TODO. Un job que pase todos los días cada `x` horas.

**Comment by JJ** [comment]
De hecho, esta mañana he hecho un programa, `get-versions.pl`, que te saca
todas las versiones de un fichero y los valores de los mismos... podíamos
hacer lo mismo para el csv y sacar lo de las subidas y bajadas.

El 21 de enero de 2015, 20:29, Javier Carrillo <notifications@github.com>
escribió:

> Hostia, eso valdría para el webservice del que hablas en el TODO. Un job
> que pase todos los días cada x horas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/4#issuecomment-70904576>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
Yo lo que pasa es que estoy pegado en PERL :facepunch:. Pero, de todas formas, se podrían coger los `json` y meterlos en una `mongodb`. A partir de ahi es cuestión de acumular datos. Hablando de búsquedas se puede hacer prácticamente lo que se quiera. 

Una cosa, si quiero saber cómo estas sacando los datos por ¿donde empiezo? ¿mirando tu [fork](https://github.com/JJ/top-github-users) verdad? 

A ver si este finde me da lugar y te hago un fork con alguna propuesta

**Comment by JJ** [comment]
No, todos los scripts están ahí, a cascoporro...
Lo de MongoDB lo estaba pensando, pero he visto DBaaS y tienen poco
espacio. Y de todas formas la info está ya en el repo Git... en el
subdirectorio `../data` está toda en JSON y CSV.

**Comment by stringparser** [comment]
Ok, miraré tranquilamente. 

Hablando de hosting o alguna solución por el camino se podría usar [nitrous.io](https://www.nitrous.io) acabo de comprobar y te dejan una "caja" gratis con 500MB de ram y 2500MB de disco duro. Tiene un editor + consola directamente en la web o te puedes logear con ssh. 

El editor es como google docs, varios pueden editar a la vez.

Una [prueba](http://github-users-186371.euw1-2.nitrousbox.com/)

**Comment by JJ** [comment]
Si se pudiera acceder directamente al repo git ahí, sería genial. Yo estuve
considerando heroku y similares, pero en el despliegue no te dejan acceder
al repo, sólo a los ficheros.
En todo caso, lo que veáis,

El 21 de enero de 2015, 22:45, Javier Carrillo <notifications@github.com>
escribió:

> Ok, miraré tranquilamente.
>
> Hablando de hosting o alguna solución por el camino se podría usar
> nitrous.io <https://www.nitrous.io> acabo de comprobar y te dejan una
> "caja" gratis con 500MB de ram y 2500MB de disco duro. Tiene un editor +
> consola directamente en la web o te puedes logear con ssh.
>
> El editor es como google docs, varios pueden editar a la vez.
>
> Una prueba <http://github-users-186371.euw1-2.nitrousbox.com/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/4#issuecomment-70928079>
> .
>



-- 
JJ

**Comment by iblancasa** [comment]
@JJ , ¿no se podría ejecutar un script o algo que copie la carpeta .git y la llame, por ejemplo "git"? Así podríamos acceder a los ficheros del repo ¿no?

**Comment by JJ** [comment]
Si tuviéramos que usar heroku a la fuerza, podía ser una opción... pero no
sé si merece la pena, es mejor un PaaS que sí nos deje acceso a .git. Igual
con OpenShift o Nitrous se puede.

**Comment by stringparser** [comment]
Nitrous esta muy bien pero acabo de darme cuenta de que intermitentemente apagan la máquina si no pagas. Yo tengo una cuenta básica (19$), y mientras se busca una mejor solución puedo poner una maquinita a funcionar para esto.

Hablando de "si se puede acceder al repo git ahí", por supuesto. Si el terminal que tienen es linux con lo básico preinstalado. Lo mejor es que te registres y lo veas, esta muy bien.

**Comment by iblancasa** [comment]
@stringparser en Heroku y OpenShift pasa igual... la máquina queda suspendida y, cuando llega una visita, echa a andar. Si llega una segunda visita, el tiempo de espera es razonable, pero para el que llega el primero... ¡puff...!

**Comment by stringparser** [comment]
Si es normal, no te van dar todo gratis. La cuenta que hice para probar esto era gratuita y por eso se cae de vez en cuando. La que tengo normal la verdad es que va muy bien.

**Comment by JJ** [comment]
No, heroku y Openshift no se paran, únicamente te dan un nodo que no tiene
muchos recursos.

El 22 de enero de 2015, 21:12, Javier Carrillo <notifications@github.com>
escribió:

> Si es normal, no te van dar todo gratis. La cuenta que hice para probar
> esto era gratuita y por eso se cae de vez en cuando. La que tengo normal la
> verdad es que va muy bien.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/4#issuecomment-71089813>
> .
>



-- 
JJ

**Comment by iblancasa** [comment]
@JJ , pensaba que era eso lo que pasaba cuando la aplicación pasa sola al estado "idle" (en OpenShift, en Heroku no sé cómo se llama) ya que eso pasa cuando lleva mucho rato sin recibir visitas... y cuando recibe una, en el panel de control aparece "started"

**Comment by stringparser** [comment]
@JJ Claro y estos te dan recursos pero te desconectan cuando ven que no la usas :smile:

**Comment by JJ** [comment]
@stringparser @iblancasa de todas formas, no veo un gran problema... se
publica en openshift o heroku y si no la visita nadie, qué le vamos a
hacer...

2015-01-23 0:00 GMT+01:00 Javier Carrillo <notifications@github.com>:

> @JJ <https://github.com/JJ> Claro y estos te dan recursos pero te
> desconectan cuando ven que no la usas [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/4#issuecomment-71117078>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
@JJ jajaja, si si yo pienso igual :+1:

**Comment by stringparser** [comment]
@JJ no se me olvida lo que escribi aqui. Este mes esta siendo muy liao en el trabajo. En cuanto saque un rato se lo hecho a esto

**Comment by iblancasa** [comment]
Y... ¿por qué no usamos un Fiware? :grin:

**Comment by JJ** [comment]
Pero ¿ya funcionan?

2015-02-05 22:16 GMT+01:00 Israel Blancas <notifications@github.com>:

> Y... ¿por qué no usamos un Fiware? [image: :grin:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/4#issuecomment-73130455>
> .
>



-- 
JJ

**Comment by iblancasa** [comment]
Creo que puedo echar a andar una. Con mucha paciencia, eso sí

**Comment by iblancasa** [comment]
@JJ ya está creada. Te he enviado las credenciales :octocat:
