### ISSUE TITLE
Next meeting: February 6?

### ISSUE THREAD

**Issue by JJ** [JJ/top-github-users-data#6]
Can be at the Free Software Office (C/ Real de Cartuja) and then we can proceed to Meninas for beers. Can @stringparser give a talk on @meteorjs, for instance?
With this, I think we can close issue #2

**Comment by stringparser** [comment]
Looks good to me. I can give a [meteor/meteor](https://github.com/meteor/meteor) intro of sorts, yes. Though I may end up talking more about node, packaging and the browser if thats all right :smile_cat:?

**Comment by JJ** [comment]
Sure! Whatever rocks your boat. What do @m42 @fdavidcl @psicobyte @renatolrr and the rest think?

**Comment by iblancasa** [comment]
I don't know... Febrary 10 I have the most difficult exam...

**Comment by stringparser** [comment]
Maybe after the exam period?

**Comment by JJ** [comment]
Every date has its own problems. I'd rather have it every month, with people coming and going, than postpone it until everyone is ready. @iblancasa , maybe you can prepare something for the first Friday in March.

**Comment by iblancasa** [comment]
@JJ For example...?

**Comment by JJ** [comment]
Intro to Fiware? (If it's still working) TweetMonuments? Socket.io? Whatever you want, really...

**Comment by iblancasa** [comment]
Socket.io it's a good topic :neckbeard:

**Comment by rafael1193** [comment]
I'm ok with the date :+1:

**Comment by JJ** [comment]
socket.io it is :-) For first Friday in March, March 6th again.

**Comment by psicobyte** [comment]
:+1:

**Comment by fdavidcl** [comment]
Feb 6 is fine for me :smile:. Maybe @ncordon is also interested?

**Comment by NCordon** [comment]
Sure! Feb 6 is also ok for me :+1:
