### ISSUE TITLE
GitHub meetup #2

### ISSUE THREAD

**Issue by JJ** [JJ/top-github-users-data#7]
Where
--------

February 6, 7:00 PM, [Free Software Office](http://osl.ugr.es).

What
------

* General introduction to the @github crowd in Granada
* Intro to @meteorjs, packaging, node, browser, and a bit of this and that by @stringparser
* Local craft beer at El Sur de Granada

Who
-----

Everyone is invited, whether you are in @github or not, but specially @stringparser, @iblancasa, @rafael1193, @psicobyte, @renatolrr, @makova, @fdavidcl, @ncordon, @m42, @eparejatobes, @pablopareja, @vterron, @pleonex, @ernestoalejo, @oskyar, @oxcar103, @algui91, @potray, @antorof, @fergunet, @demiurgosoft, @josecolella, @rafael1193, @unintendedbear, @agarciamontoro, @torresj, @josemlp91, @juanafernandez @ivanortegaalba y @franexposito. 

Why
--------

We githubbers will be meeting every first Friday of every month, at the @oslugr or anywhere for technical and trash talking. We'll do it in Spanish or English, depending on what language is the best for all parties involved. This issue closes #6.

**Comment by unintendedbear** [comment]
Totally agree. See you there, guys!

**Comment by fergunet** [comment]
+1!

**Comment by juanAFernandez** [comment]
It sounds good!

**Comment by oxcar103** [comment]
:+1:

**Comment by Makova** [comment]
Ser you :-)

**Comment by psicobyte** [comment]
:+1:  :D

**Comment by stringparser** [comment]
oh yeahh

**Comment by josecolella** [comment]
Can’t make it. In Detroit until late May…Have fun though!!!

Jose Colella
josecolella@yahoo.com

**Comment by stringparser** [comment]
that's really nice, enjoy it there!

**Comment by agarciamontoro** [comment]
It sounds really good :+1: See you there after the exam I'll take that afternoon :)
@analca3 is also coming!

**Comment by ivanortegaalba** [comment]
:+1: Come on!

**Comment by vterron** [comment]
+1

**Comment by JJ** [comment]
¡Mañana nos vemos! Ya hemos recibido pegatinas de @github y una buena cantidad de otras que me he traído del FOSDEM.

**Comment by Makova** [comment]
Y nosotros de recogida :(

**Comment by JJ** [comment]
Es por la tarde, Manu.

**Comment by stringparser** [comment]
Yeahh, que ganicas de echar un rato bueno el viernes

**Comment by franexposito** [comment]
Allí estaré ;)

**Comment by vterron** [comment]
¿La dirección exacta de la OSL cuál es? No la veo en la página web.

**Comment by oskyar** [comment]
En osl.ugr.es la puedes encontrar.

**Comment by iblancasa** [comment]
@vterron Cartuja 36 y 38. Planta baja

**Comment by vterron** [comment]
Muchas gracias, @iblancasa.

**Comment by potray** [comment]
Yo no podré asistir, tengo un examen el día 9 y está chungo de narices :(

2015-02-06 16:38 GMT+01:00 Víctor Terrón <notifications@github.com>:

> Muchas gracias, @iblancasa <https://github.com/iblancasa>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/7#issuecomment-73255427>
> .
>



-- 
Daniel Díaz Salas
Máster Universitario en Ingeniería Informática

**Comment by JJ** [comment]
Si alguien quiere postear sus fotos, aquí mismo puede hacerse...

**Comment by stringparser** [comment]
Repositorio que se suponía iba a utilizar: 
  - [github.com/stringparser/osl-granada-meteorjs](https://github.com/stringparser/osl-granada-meteorjs)

Lo iré documentando entre hoy y mañana. @JJ mas tarde abro un issue pa escribir la crónica (aunque sigo pensando que tienes más labia tu, gañán)

Y para los interesados en aprender, contribuir y echar el rato, he pensado en utilizar el modelo [Open Open Source Project](https://github.com/rvagg/node-levelup#contributing) para el repostorio de arriba. 

En corto: quien haga un pull con un valor significante se hace owner del repositorio junto con los que haya en ese momento.

**Comment by JJ** [comment]
¡Gracias!

**Comment by JJ** [comment]
Estoy pensando más bien en montar algo parecido a esto
JJ/FOSDEM-lightning-2015 pero en una sola página con Meteor. ¿Me podrías
echar una mano?

**Comment by stringparser** [comment]
¡Por supuesto! En verdad, estaba pensando que estaría bien tener un repositorio donde poner la documentación de las charlas en general, no de una en concreto. ¿Eso es algo que tiene interés?

**Comment by stringparser** [comment]
Quiero decir, que te parece un JJ/github-users-talks o un JJ/github-users como cajón desastre a organizar?

**Comment by JJ** [comment]
Se puede crear directamente una organización, github-users-grx y añadir a
todo el que lo pida...

2015-02-07 13:30 GMT+01:00 Javier Carrillo <notifications@github.com>:

> Quiero decir, que te parece un JJ/github-users-talks o un JJ/github-users
> como cajón desastre a organizar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/7#issuecomment-73362401>
> .
>



-- 
JJ

**Comment by JJ** [comment]
hala, hecho. Estáis todos invitados y podéis invitar a más.

**Comment by iblancasa** [comment]
En lo que nos llega algún diseñador, podríamos ponerle [algún avatar](http://fotos.subefotos.com/a0420f7d45526689657ea2562edc4247o.jpg)

**Comment by JJ** [comment]
:-) Qué bueno...

El 7 de febrero de 2015, 14:00, Israel Blancas <notifications@github.com>
escribió:

> En lo que nos llega algún diseñador, podríamos ponerle algún avatar
> <http://fotos.subefotos.com/a0420f7d45526689657ea2562edc4247o.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/7#issuecomment-73363324>
> .
>



-- 
JJ

**Comment by stringparser** [comment]
ese mola más que el que yo había puesto :dancer:

**Comment by stringparser** [comment]
@JJ @iblancasa ale ya hay avatar

**Comment by stringparser** [comment]
@JJ he puesto el nombre en minúsculas, espero no te importe. No se porqué pero veía el  nombre incómodo en mayúsculas

**Comment by JJ** [comment]
Ya decía yo que había cambiado. sin problemas.

El 7 de febrero de 2015, 14:27, Javier Carrillo <notifications@github.com>
escribió:

> @JJ <https://github.com/JJ> he puesto el nombre en minúsculas, espero no
> te importe. No se porqué pero veía el nombre incómodo en mayúsculas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JJ/top-github-users-data/issues/7#issuecomment-73364223>
> .
>



-- 
JJ

**Comment by ivanortegaalba** [comment]
@JJ invitame a github-users-grx =)

**Comment by stringparser** [comment]
creo que estás invitado, voy a mirar... si [apareces como miembror](http://github.com/github-users-grx) xD

**Comment by ivanortegaalba** [comment]
@stringparser ya me invitó @JJ esta mañana! =)  Antes no estaba...

**Comment by stringparser** [comment]
ahm! cachis :D

**Comment by JJ** [comment]
Si no tenéis más fotos que añadir, voy cerrando. ¡Atentos al siguiente!
