### ISSUE TITLE
Top Spain and category

### ISSUE THREAD

**Issue by CKGrafico** [JJ/top-github-users-data#8]
Creo que puede ser muy interesante tener top por categoria de toda España, he ido ciudad por ciudad mirando gente de JavaScript que seguir y seria interesante tenerlos todos juntos

**Comment by JJ** [comment]
El problema es buscar patrones + filtros únicos por provincia, pero sí, lo intentaremos.

**Comment by fernand0** [comment]
¿Los usuarios se añaden 'a mano' como resultado de búsquedas? ¿O hay algún programa para eso que no veo?

**Comment by JJ** [comment]
Simplemente poniendo su ciudad o provincia (o las dos) en el perfil.

Ya te echaba yo de menos ;-)

**Comment by fernand0** [comment]
Y ¿cómo se añaden a tu conjunto de datos?

**Comment by JJ** [comment]
Tengo que añadir la provincia con el criterio de búsqueda correspondiente. En todo caso, podemos hacer un agregado por lenguaje, como nos piden...

**Comment by JJ** [comment]
Si tenéis cualquier sugerencia sobre el código, en el repo correspondiente, por favor https://github.com/JJ/github-city-rankings
