### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by CKGrafico** [JJ/top-github-users-data#9]
¿Tienes todo en un sitio privado?
¿Por que no haces una o varias ramas con el código e implementas TravisCI para que se ejecute todo ahí?

**Comment by pleonex** [comment]
The code can be found here: [JJ/github-city-rankings](https://github.com/JJ/github-city-rankings).
It could be a good idea to add links in the README of both repos.

**Comment by CKGrafico** [comment]
Thanks :beer:
